#  ruby function field_is_divided(tiles, dir_vector), that returns true if a car can't move in dir_vector direction, false if a car can move so.
# a car can't move to a tile when it is :grass.
# a car can't move that way if in every row there's a tile that's :grass, and that we could find grass tiles that are connected vertically from top to bottom (two tiles could be connected when they are neigbors diagonally as well as when they are neighbors horizontally or vertically), like in tiles1 below.

# tiles form a rectangular field of tiles and every tile may have cars on it that can move to an adjacent tile.
# every tile has :x and :y.
# you could have for example: tiles1 = [{:x=>0, :y=>0, :grass=>false}, {:x=>1, :y=>0, :grass=>false}, {:x=>2, :y=>0, :grass=>false}, {:x=>3, :y=>0, :grass=>false}, {:x=>4, :y=>0, :grass=>true}, {:x=>5, :y=>0, :grass=>false}, {:x=>6, :y=>0, :grass=>false}, {:x=>0, :y=>1, :grass=>false}, {:x=>1, :y=>1, :grass=>false}, {:x=>2, :y=>1, :grass=>false}, {:x=>3, :y=>1, :grass=>false}, {:x=>4, :y=>1, :grass=>false}, {:x=>5, :y=>1, :grass=>true}, {:x=>6, :y=>1, :grass=>false}, {:x=>0, :y=>2, :grass=>false}, {:x=>1, :y=>2, :grass=>false}, {:x=>2, :y=>2, :grass=>false}, {:x=>3, :y=>2, :grass=>false}, {:x=>4, :y=>2, :grass=>false}, {:x=>5, :y=>2, :grass=>true}, {:x=>6, :y=>2, :grass=>false}, {:x=>0, :y=>3, :grass=>false}, {:x=>1, :y=>3, :grass=>false}, {:x=>2, :y=>3, :grass=>false}, {:x=>3, :y=>3, :grass=>false}, {:x=>4, :y=>3, :grass=>true}, {:x=>5, :y=>3, :grass=>false}, {:x=>6, :y=>3, :grass=>false}, {:x=>0, :y=>4, :grass=>false}, {:x=>1, :y=>4, :grass=>false}, {:x=>2, :y=>4, :grass=>false}, {:x=>3, :y=>4, :grass=>true}, {:x=>4, :y=>4, :grass=>false}, {:x=>5, :y=>4, :grass=>false}, {:x=>6, :y=>4, :grass=>false}]
#in this case field_is_divided(tiles1) is true.
# but for tiles2 = [{:x=>0, :y=>0, :grass=>false}, {:x=>1, :y=>0, :grass=>false}, {:x=>2, :y=>0, :grass=>false}, {:x=>3, :y=>0, :grass=>false}, {:x=>4, :y=>0, :grass=>true}, {:x=>5, :y=>0, :grass=>false}, {:x=>6, :y=>0, :grass=>false}, {:x=>0, :y=>1, :grass=>false}, {:x=>1, :y=>1, :grass=>false}, {:x=>2, :y=>1, :grass=>false}, {:x=>3, :y=>1, :grass=>false}, {:x=>4, :y=>1, :grass=>false}, {:x=>5, :y=>1, :grass=>true}, {:x=>6, :y=>1, :grass=>false}, {:x=>0, :y=>2, :grass=>false}, {:x=>1, :y=>2, :grass=>false}, {:x=>2, :y=>2, :grass=>false}, {:x=>3, :y=>2, :grass=>false}, {:x=>4, :y=>2, :grass=>false}, {:x=>5, :y=>2, :grass=>true}, {:x=>6, :y=>2, :grass=>false}, {:x=>0, :y=>3, :grass=>false}, {:x=>1, :y=>3, :grass=>false}, {:x=>2, :y=>3, :grass=>false}, {:x=>3, :y=>3, :grass=>false}, {:x=>4, :y=>3, :grass=>true}, {:x=>5, :y=>3, :grass=>false}, {:x=>6, :y=>3, :grass=>false}, {:x=>0, :y=>4, :grass=>false}, {:x=>1, :y=>4, :grass=>false}, {:x=>2, :y=>4, :grass=>false}, {:x=>3, :y=>4, :grass=>false}, {:x=>4, :y=>4, :grass=>false}, {:x=>5, :y=>4, :grass=>false}, {:x=>6, :y=>4, :grass=>true}]
#field_is_divides(tiles2) is false.
